on: push
name: Build and Validate
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: nuxt/actions-yarn@master
      with:
        args: install
    - name: Validate
      uses: nuxt/actions-yarn@master
      with:
        args: validate
