on: push
name: Build, Test, and Publish
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@master
      with:
        args: install
    - name: Validate
      uses: actions/npm@master
      with:
        args: validate
